<?php

if($_GET )
{
  print_r('<h1>'.$_GET['lan']."</h1>");
}

?>
<?php if(isset($success)) {?>
<div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php echo $message; 
   ?>
</div>
<?php }?>
<h2>Exsisting Roles Table</h2>
<?php echo $this->locale->_('Exsisting Roles Table');?>


<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($roles as $key=>$value)
        {
            echo "<tr><th scope='row'>$value->id</th><td>$value->role</td></tr>";
        }?>
  </tbody>
</table>

<h2>Add Roles using this form</h2>



<?php echo $this->tag->form(""); ?>

<p>
        <label for="name">Role </label>
        <?php echo $this->tag->textField("role"); ?>
</p>
<p>
    <?php echo $this->tag->submitButton("Add Role"); ?>
</p>

    


</form>