<?php

echo "<h1>Hello World</h1>";

echo PHP_EOL;


echo "<p>";
echo $this->tag->linkTo(
    'products',
    'List All Products'
);
echo "</p>";

echo "<p>";
echo $this->tag->linkTo(
    'products/add',
    'Add New Product'
);
echo "</p>";

echo "<p>";
echo $this->tag->linkTo(
    'orders',
    'List All Orders'
);
echo "</p>";

echo "<p>";
echo $this->tag->linkTo(
    'orders/add',
    'Add New Order'
);
echo "</p>";


echo "<p>";
echo $this->tag->linkTo(
    '/index/Settings',
    'Settings'
);
echo "</p>";
